### ISSUE TITLE
Randomly crash on android

### ISSUE THREAD

**Issue by soramister** [jofr/capacitor-media-session#19]
Hello,

I have been having random crash on first update of the MediaSession.

I have created the following PR which fix the issue : 
https://github.com/jofr/capacitor-media-session/pull/18

I don't know why it happened by the variables in this PR were null, which crashes the application. I have added a check to be sure it is not null. This prevent the crash.

There must be a better way to fix it, but I found this one does.

Let me know if you have any questions.

**Comment by jofr** [comment]
Thank you for the fix @soramister, it is now merged and a new version of the plugin has been published. I'll leave this issue open to further investigate why those variables are null (for which I don't have the time right now).

**Comment by fabian-meisinger** [comment]
I recently started using this plugin and see the following crash reported in Crashlytics:
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean io.github.jofr.capacitor.mediasessionplugin.MediaSessionPlugin.hasActionHandler(java.lang.String)' on a null object reference
       at io.github.jofr.capacitor.mediasessionplugin.MediaSessionService.update(MediaSessionService.java:233)
       at io.github.jofr.capacitor.mediasessionplugin.MediaSessionService.updatePossibleActions(MediaSessionService.java:301)
       at io.github.jofr.capacitor.mediasessionplugin.MediaSessionPlugin.setActionHandler(MediaSessionPlugin.java:195)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138)
       at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:774)
       at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA()
       at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(:8)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```
From the looks of it this seems to be a threading issue and `MediaSessionService.update` sometimes gets called before `MediaSessionService.connectAndInitialize` has finished. Otherwise I don't know why `plugin` would be null in that line.
Maybe you could move the assignment of `this.plugin` to the end of `connectAndInitialize` and use it to determine if the service has fully initialized by checking if `plugin` is null before running anything else in the `update` method?
