### ISSUE TITLE
The application could not be installed: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED

### ISSUE THREAD

**Issue by sanderschnydrig** [jofr/capacitor-media-session#3]
# Platform
Android 13 Pixel 6 (Emulator)

# Plugin Version
1.0.3

# Issue
When adding this plugin for Capacitor 3 and building with Android Studio with API target version 31 I'm getting the following error:

```console
11/29 11:59:42: Launching 'app' on Pixel 6 API 33.
Installation did not succeed.
The application could not be installed: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED

List of apks:
[0] '/Users/user/git/app/android/app/build/outputs/apk/debug/app-debug.apk'
Installation failed due to: 'INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl2092652939.tmp/base.apk (at Binary XML file line #89): androidx.media.session.MediaButtonReceiver: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present'
Retry
Failed to launch an application on all devices
```

# AndroidManifest.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="ch.pomona.newsapp">
    <application android:allowBackup="true" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:roundIcon="@mipmap/ic_launcher_round" android:supportsRtl="true" android:usesCleartextTraffic="true" android:theme="@style/AppTheme">
        <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/push"/>

        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode" android:name="ch.pomona.newsapp.MainActivity" android:label="@string/title_activity_main" android:theme="@style/AppTheme.NoActionBarLaunch" android:windowSoftInputMode="adjustPan" android:exported="true" android:launchMode="singleTask">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>

            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:host="${hostName}" android:scheme="https"/>
            </intent-filter>
        </activity>

        <provider android:name="androidx.core.content.FileProvider" android:authorities="${applicationId}.fileprovider" android:exported="false" android:grantUriPermissions="true">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/file_paths"/>
        </provider>
    </application>

    <!-- Permissions -->
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="com.android.vending.BILLING"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>
</manifest>
```

# variables.gradle
```gradle
ext {
    minSdkVersion = 22
    compileSdkVersion = 30
    targetSdkVersion = 31
    androidxActivityVersion = '1.2.0'
    androidxAppCompatVersion = '1.2.0'
    androidxCoordinatorLayoutVersion = '1.1.0'
    androidxCoreVersion = '1.3.2'
    androidxFragmentVersion = '1.3.0'
    junitVersion = '4.13.1'
    androidxJunitVersion = '1.1.2'
    androidxEspressoCoreVersion = '3.3.0'
    cordovaAndroidVersion = '7.0.0'
}
```

# build.gradle
```gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {

    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.3'
        classpath 'com.google.gms:google-services:4.3.10'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

apply from: "variables.gradle"

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```
# app/build.gradle
```gradle
apply plugin: 'com.android.application'

def loadProperties = { filename -> 
    def properties = new Properties()
    file(filename).withInputStream {
        properties.load(it)
    }
    return properties
}

def ENV = System.getenv()
def KEYSTORE_PATH = ENV["KEYSTORE_PATH"]
def KEYSTORE_ALIAS = ENV["KEYSTORE_ALIAS"]
def KEYSTORE_PASSWORD = ENV["KEYSTORE_PASSWORD"]

def TARGET = loadProperties('../target.properties')
def BASE_URL = TARGET.BASE_URL

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    defaultConfig {
        applicationId "ch.pomona.newsapp"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 2080401
        versionName "2.8.4"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        aaptOptions {
             // Files and dirs to omit from the packaged assets dir, modified to accommodate modern web apps.
             // Default: https://android.googlesource.com/platform/frameworks/base/+/282e181b58cf72b6ca770dc7ca5f91f135444502/tools/aapt/AaptAssets.cpp#61
            ignoreAssetsPattern '!.svn:!.git:!.ds_store:!*.scc:.*:!CVS:!thumbs.db:!picasa.ini:!*~'
        }
        manifestPlaceholders = [hostName:"$BASE_URL"]
    }
    signingConfigs {
        release {
            // We can leave these in environment variables
            storeFile file("$KEYSTORE_PATH")
            keyAlias "$KEYSTORE_ALIAS"

            // These two lines make gradle believe that the signingConfigs
            // section is complete. Without them, tasks like installRelease
            // will not be available!
            storePassword "$KEYSTORE_PASSWORD"
            keyPassword "$KEYSTORE_PASSWORD"
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }
}

repositories {
    flatDir{
        dirs '../capacitor-cordova-android-plugins/src/main/libs', 'libs'
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation("androidx.appcompat:appcompat:$androidxAppCompatVersion") {
        force = true
    }
    implementation project(':capacitor-android')
    implementation 'androidx.webkit:webkit:1.4.0'
    testImplementation "junit:junit:$junitVersion"
    androidTestImplementation "androidx.test.ext:junit:$androidxJunitVersion"
    androidTestImplementation "androidx.test.espresso:espresso-core:$androidxEspressoCoreVersion"
    implementation project(':capacitor-cordova-android-plugins')
    // Import the BoM for the Firebase platform
    implementation platform('com.google.firebase:firebase-bom:28.4.2')
    // Declare the dependencies for the Firebase Cloud Messaging and Analytics libraries
    // When using the BoM, you don't specify versions in Firebase library dependencies
    // implementation 'com.google.firebase:firebase-messaging'
    implementation 'com.google.firebase:firebase-analytics'
    implementation "com.google.firebase:firebase-iid"
}

apply from: 'capacitor.build.gradle'

try {
    def servicesJSON = file('google-services.json')
    if (servicesJSON.text) {
        apply plugin: 'com.google.gms.google-services'
    }
} catch(Exception e) {
    logger.warn("google-services.json not found, google-services plugin not applied. Push Notifications won't work")
}

```

# Capacitor Doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.5.0
  @capacitor/core: 4.5.0
  @capacitor/android: 4.5.0
  @capacitor/ios: 4.5.0

Installed Dependencies:

  @capacitor/cli: 3.2.5
  @capacitor/android: 3.9.0
  @capacitor/ios: 3.9.0
  @capacitor/core: 3.9.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

**Comment by sanderschnydrig** [comment]
As a workaround I'm replacing the AndroidManifest.xml from the plugin with one that contains the android:exported="true" flag in the receiver.

However the notification does not show up when calling 

```typescript
      await MediaSession.setMetadata({
        title: 'Prelude',
        artist: 'Jan Morgenstern',
        album: 'Big Buck Bunny',
        artwork: [
          { src: './assets/imgs/logo.png', type: 'image/png', sizes: '512x512' }
        ]
      })
```

**Comment by sanderschnydrig** [comment]
So it seem its working on Android < 12 API Level 30 but on API Level 31 and onwards its crashing the app and I'm getting this error:

```console
FATAL EXCEPTION: main
 Process: com.example.app, PID: 20157
 android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{2960294 u0 com.example.app/io.github.jofr.capacitor.mediasessionplugin.MediaSessionService}
  at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2006)
  at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1977)
  at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2242)
  at android.os.Handler.dispatchMessage(Handler.java:106)
  at android.os.Looper.loopOnce(Looper.java:201)
  at android.os.Looper.loop(Looper.java:288)
  at android.app.ActivityThread.main(ActivityThread.java:7898)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by jofr** [comment]
Hi, so as capacitor 3 is targeting level 30 per default and capacitor 4 is targeting level 32 the `android:exported = "true"` was only included in the capacitor 4 version of the plugin (because setting that became mandatory with level 31). But it's no problem to include this even if targeting a lower API level so I've added this just now also to the capacitor 3 version (published as version 1.0.4, also including some other fixes).

I am not sure though why the notification is not showing and the app is crashing for you. From the error (ForegroundServiceDidNotStartInTimeException) it seems like the foreground service is taking too long to start up: Android gives the service 5 seconds after starting to call startForeground() and provide a notification that should be associated with this foreground service (the media notification in this case) so the user knows the app is performing a task. If this does not happen in those 5 seconds this error occurs but it actually never happened to me yet.

Do you have a complete minimal example of an app where this error occurs?

**Comment by sanderschnydrig** [comment]
Hi @jofr
Thanks for your response.
The build.gradle setting for API Level 31 is required by Google in order to upload new builds to the Play Store (requirement since November). So I'm sure lots of people would benefit from that change.

I will try to make a reproduction as soon as I get around to it and get back to you.

**Comment by sanderschnydrig** [comment]
Hi @jofr 

It's working for us now on Capacitor v4 and version 2 of this plugin. We also had the event handlers and listeners wired up differently in the past which I updated to reflect your example here.

Thanks a bunch for your support!

As far as we're concerned this issue can be closed now.

Best regards
